# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build electron

on:
  push:
    branches:
      - dummy-main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name 'Github'
      - run: yarn version --patch --no-git-commit
      - run: docker run --rm
           --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_')
           --env ELECTRON_CACHE="/root/.cache/electron"
           --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder"
           --env GH_TOKEN=${{ secrets.GH_TOKEN }}
           -v ${PWD}:/project
           -v ${PWD##*/}-node-modules:/project/node_modules
           -v ~/.cache/electron:/root/.cache/electron
           -v ~/.cache/electron-builder:/root/.cache/electron-builder
           electronuserland/builder:wine yarn build --win --linux
      - run: git checkout build-results || git checkout -b build-results
      - run: git add --force build/searchable-pdf-*.exe
      - run: git commit -m "Built `jq '.version' package.json`" 
      - run: git push -u origin build-results

          

