# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build electron

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: electronuserland/builder:wine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-yarn@v1
        with:
          node-version: 12
      - run: yarn build --win --linux
      - uses: actions/upload-artifact@v2
        with:
          name: windows-latest
          path: build/*.exe

